'use client';

import { Check, ChevronLeft, ChevronRight, Clock3, FlaskConical, ShieldCheck } from 'lucide-react';
import styles from './lab-desk.module.css';

export type TenantLab = {
  title: string;
  time: string;
  area: string;
  goal: string;
  beforeYouBegin: string;
  tasks: string[];
  evidence: string;
  pitfall: string;
  cleanup: string;
  debrief: string;
};

export const labs: TenantLab[] = [
  { title: 'Entra access at the right scope', time: '40 min', area: 'Identity', goal: 'Practice a least-privileged assignment and interpret where it takes effect.', beforeYouBegin: 'Use a non-production subscription and a temporary group. You need permission to create a resource group and assign roles at that resource-group scope.', tasks: ['Create a temporary group or use a test group.', 'Create rg-az104-identity and assign Reader to that group at resource-group scope.', 'Compare access assignments at the resource group and subscription.', 'Remove the role assignment, membership, and resource group.'], evidence: 'You can show that the group can read only the target resource group, then explain why the assignment does not grant visibility in an unrelated resource group.', pitfall: 'Directory roles manage Microsoft Entra objects; Azure RBAC roles authorize Azure resource actions. A broader subscription assignment inherits downward.', cleanup: 'Remove the role assignment and test membership, then delete rg-az104-identity.', debrief: 'Identity proves who is calling; Azure RBAC decides what that identity can do at a scope. Inheritance goes downward, not sideways.' },
  { title: 'Govern a small platform', time: '45 min', area: 'Governance', goal: 'Use guardrails without confusing what each one controls.', beforeYouBegin: 'Use a disposable resource group. Do not assign broad policies or locks to a shared subscription while learning.', tasks: ['Create a tagged temporary resource group with CostCenter and Environment.', 'Assign a tag requirement policy and inspect the compliance state.', 'Add a CanNotDelete lock and observe the blocked management-plane deletion.', 'Create a budget alert and record the notification configuration.'], evidence: 'You can point to policy compliance, the deletion block created by the lock, and the budget notification threshold as three separate results.', pitfall: 'A budget notifies about cost; it does not stop spending. A lock does not grant permissions, and Policy is not an access-control system.', cleanup: 'Remove the lock and policy assignment, remove the budget, then delete the temporary resource group.', debrief: 'Policy evaluates standards, locks protect management operations, tags describe resources, and budgets notify about spend.' },
  { title: 'Blob storage with a recovery story', time: '50 min', area: 'Storage', goal: 'Make a private container recoverable and grant a short limited handoff.', beforeYouBegin: 'Choose a temporary storage-account name and check pricing/region availability. Use a harmless sample text file only.', tasks: ['Create a storage account and compare available redundancy choices.', 'Create a private container; upload then overwrite a sample file.', 'Enable versioning and soft delete, then recover the earlier version.', 'Generate a short-lived HTTPS-only SAS with only the needed permission.'], evidence: 'You can recover the earlier version after an overwrite and explain the SAS resource, permission, protocol, and expiry boundaries.', pitfall: 'Versioning protects overwritten data; soft delete protects deleted data. Neither replaces a deliberate redundancy choice.', cleanup: 'Revoke or let the SAS expire, then delete the storage account and its temporary resource group.', debrief: 'Versioning handles overwrites; soft delete handles deletion. A SAS is narrow delegation, not a replacement for identity-based access.' },
  { title: 'Azure Files and access choices', time: '45 min', area: 'Storage', goal: 'Compare a shared file system with object storage and map its recovery tools.', beforeYouBegin: 'Use a temporary storage account. Keep the exercise to a small file share and sample files.', tasks: ['Create a file share and inspect protocol and quota settings.', 'Review identity-based access options for Azure Files.', 'Create a file-share snapshot or walk through the supported restore path.', 'Write one sentence explaining why a blob container is not a file share.'], evidence: 'You can name the file-share protocol/access model and identify the snapshot or soft-delete path you would use for point-in-time recovery.', pitfall: 'Azure Files is a managed SMB/NFS share; Blob Storage is object storage. A blob lifecycle rule is not file-share recovery.', cleanup: 'Delete the file share and storage account, including any test snapshot, when you have captured your notes.', debrief: 'Azure Files provides a managed file-share interface; Blob Storage is object storage. Choose from the workload access pattern.' },
  { title: 'Bicep deployment reading drill', time: '45 min', area: 'Compute', goal: 'Move from clicking resources to understanding a declarative deployment.', beforeYouBegin: 'Create a new temporary resource group and work with a minimal storage-account Bicep definition. Do not copy secrets into the file.', tasks: ['Create a minimal Bicep file for a storage account.', 'Identify parameters, resources, outputs, and a dependency.', 'Deploy to a temporary resource group, change one parameter, and redeploy.', 'Inspect deployment history and the resulting resource.'], evidence: 'You can identify which input is changeable at deployment time, what resource is declared, and what output a script could consume.', pitfall: 'Bicep declares intended state; it is not a recording of portal clicks. Deployment history is the evidence for the control-plane operation.', cleanup: 'Delete the temporary resource group and remove any locally saved sample values that should not be retained.', debrief: 'Bicep states intended end state. Expect to interpret or modify an existing definition rather than author a large template from memory.' },
  { title: 'VM availability and operations', time: '55 min', area: 'Compute', goal: 'Separate VM configuration, capacity, and availability design.', beforeYouBegin: 'This is primarily a design-and-portal inspection drill. Create a VM only if you accept its compute charges, and deallocate it promptly.', tasks: ['Compare zone, availability-set, and scale-set choices in the create flow.', 'Inspect VM sizes, managed disk options, and stop/deallocate behavior.', 'Review a VM move: resource group, subscription, and region are different moves.', 'Document which option fits a two-tier stateful app and why.'], evidence: 'You can choose a zone, availability set, or scale set from the availability and scaling requirement—not just from a familiar product name.', pitfall: 'A VM Scale Set is a homogeneous fleet. Availability zones and availability sets address different failure boundaries; neither is an automatic regional DR plan.', cleanup: 'Deallocate and delete any VM and associated public IP, disk, NIC, and resource group created for the exercise.', debrief: 'Availability zones, availability sets, and VM Scale Sets solve related but distinct resilience or scale problems.' },
  { title: 'VNet traffic path', time: '60 min', area: 'Networking', goal: 'Build a small network and prove why a flow is allowed or denied.', beforeYouBegin: 'Use RFC 1918 ranges that do not overlap with networks you may later peer. Keep all resources in one temporary resource group.', tasks: ['Create a VNet with web and data subnets, leaving room for growth.', 'Attach an NSG with one narrow rule and deliberate priority.', 'Create a route table and inspect effective routes and security rules.', 'Use Network Watcher evidence before changing a rule.'], evidence: 'You can trace one intended connection from name resolution to route selection to the security rule that permits or denies the packet.', pitfall: 'DNS chooses a name-to-IP answer, a route chooses a next hop, and an NSG filters traffic. Changing one does not repair the others.', cleanup: 'Delete the temporary resource group, including the VNet, subnets, NSG, route table, and diagnostics resources.', debrief: 'DNS names the destination, routing picks a next hop, and an NSG filters traffic. Treat each as separate evidence.' },
  { title: 'Private PaaS endpoint and DNS', time: '55 min', area: 'Networking', goal: 'Connect a PaaS resource through a private address and validate resolution.', beforeYouBegin: 'Use a supported temporary PaaS resource in a VNet you can delete. Confirm private endpoint pricing and DNS permissions first.', tasks: ['Create a supported PaaS resource and a private endpoint in the data subnet.', 'Link the suggested private DNS zone to the VNet.', 'Verify the service name resolves to the private address.', 'Compare the design with a service endpoint.'], evidence: 'The service FQDN resolves to the private endpoint IP from the linked VNet, and you can explain why the selected path is private.', pitfall: 'A service endpoint keeps the service on its public endpoint with VNet identity. A private endpoint creates a private NIC; NSG rules do not fix DNS resolution.', cleanup: 'Delete the private endpoint, DNS zone/link, PaaS resource, and temporary resource group.', debrief: 'A service endpoint keeps a public service endpoint. A private endpoint places a private NIC in your VNet, and DNS must support it.' },
  { title: 'Load balancing and secure admin access', time: '50 min', area: 'Networking', goal: 'Choose Layer 4 distribution and avoid exposing VM management ports.', beforeYouBegin: 'This can be a design drill; real load balancers and VMs may create charges. Use small temporary resources if you build it.', tasks: ['Sketch two backend VMs, a health probe, backend pool, and rule.', 'Decide whether the frontend should be internal or public.', 'Review Azure Bastion as an admin path without public SSH/RDP on each VM.', 'Use health evidence to explain a failed probe.'], evidence: 'You can label the frontend, rule, health probe, and backend pool and justify keeping direct VM administration off public IP addresses.', pitfall: 'Azure Load Balancer is Layer 4 TCP/UDP distribution. It is not an HTTP-aware Application Gateway, and a health probe is not a security rule.', cleanup: 'Delete any test load balancer, public IP, VM/Bastion resources, and the temporary resource group.', debrief: 'Load Balancer distributes TCP/UDP flows. Bastion reaches VMs without assigning public IPs to every workload VM.' },
  { title: 'Observe, alert and recover', time: '60 min', area: 'Monitor & recovery', goal: 'Make a small workload observable with a believable recovery plan.', beforeYouBegin: 'Use a small temporary workload and check any Log Analytics ingestion, alert, vault, and protected-instance costs before enabling them.', tasks: ['Create a Log Analytics workspace and inspect metrics versus logs.', 'Create a metric alert with an action group and review alert processing.', 'Compare Recovery Services and Backup vaults in the portal.', 'Choose a backup policy, identify a restore point, and document validation.'], evidence: 'You can identify the signal an alert evaluates, the action group it calls, and the restore or failover evidence that proves the recovery plan.', pitfall: 'Metrics are numeric time series; logs provide detailed queryable records. Azure Backup restores recovery points, while Site Recovery prepares replicated workloads for failover.', cleanup: 'Remove test alerts/action groups and any protected temporary resources. Follow the vault deletion prerequisites before deleting a vault.', debrief: 'A metric answers “how much, now?” A log explains context. Backup restores; Site Recovery prepares replicated workloads for failover.' },
];

export function LabDesk({ activeIndex, doneLabs, onSelect, onToggle }: { activeIndex: number; doneLabs: number[]; onSelect: (index: number) => void; onToggle: (index: number) => void }) {
  const lab = labs[activeIndex];
  const reviewed = doneLabs.includes(activeIndex);
  const choose = (index: number) => onSelect((index + labs.length) % labs.length);

  return <div className={styles.desk}>
    <aside className={styles.rail} aria-label="Tenant lab selection">
      <p className={styles.railTitle}>Choose a lab</p>
      <p className={styles.railHint}>Work one focused scenario at a time. Your review marks stay on this device.</p>
      <div className={styles.labList}>
        {labs.map((item, index) => <button type="button" key={item.title} className={index === activeIndex ? styles.labChoiceActive : styles.labChoice} aria-pressed={index === activeIndex} onClick={() => choose(index)}><span>{String(index + 1).padStart(2, '0')}</span><span><b>{item.title}</b><small>{item.area} · {item.time}</small></span>{doneLabs.includes(index) && <Check size={15} aria-label="Reviewed" />}</button>)}
      </div>
    </aside>
    <article className={styles.player} aria-live="polite" style={{ scrollMarginTop: 78 }}>
      <header className={styles.playerHeader}><div><p className={styles.kicker}>Lab {String(activeIndex + 1).padStart(2, '0')} · {lab.area}</p><h3>{lab.title}</h3><p>{lab.goal}</p></div><span className={styles.time}><Clock3 size={15} /> {lab.time}</span></header>
      <div className={styles.instructionFrame} aria-label={`${lab.title} guided instructions`}>
        <section className={styles.mission}><p className={styles.blockLabel}>Before you begin</p><p>{lab.beforeYouBegin}</p></section>
        <section><p className={styles.blockLabel}>Guided steps</p><ol className={styles.steps}>{lab.tasks.map((task, index) => <li key={task}><b>Step {index + 1}</b><span>{task}</span></li>)}</ol></section>
        <section className={styles.evidence}><ShieldCheck size={18} /><div><p className={styles.blockLabel}>Success check</p><p>{lab.evidence}</p></div></section>
        <section className={styles.pitfall}><FlaskConical size={18} /><div><p className={styles.blockLabel}>Exam trap to avoid</p><p>{lab.pitfall}</p></div></section>
        <section className={styles.cleanup}><p className={styles.blockLabel}>Clean up</p><p>{lab.cleanup}</p></section>
        <p className={styles.debrief}>{lab.debrief}</p>
      </div>
      <footer className={styles.controls}><button type="button" className={styles.previous} onClick={() => choose(activeIndex - 1)}><ChevronLeft size={16} /> Previous</button><button type="button" className={reviewed ? styles.reviewed : styles.review} onClick={() => onToggle(activeIndex)}>{reviewed ? <><Check size={16} /> Lab reviewed</> : 'Mark lab reviewed'}</button><button type="button" className={styles.next} onClick={() => choose(activeIndex + 1)}>Next <ChevronRight size={16} /></button></footer>
    </article>
  </div>;
}
