'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, BookOpen, Check, ChevronLeft, ChevronRight, CircleAlert, Clock3, ExternalLink, FlaskConical, Layers3, Network, ShieldCheck, Target } from 'lucide-react';

const topics = [
  { name: 'Identity & governance', weight: '20–25%', accent: 'cyan', focus: 'Scopes, RBAC, Policy, locks, tags, budgets, Entra users and groups.', outcomes: ['Choose the narrowest effective RBAC scope', 'Separate Policy, RBAC, tags, and locks', 'Explain inheritance from management group to resource'] },
  { name: 'Storage', weight: '15–20%', accent: 'violet', focus: 'Redundancy, access, Azure Files, Blob lifecycle, protection and transfer tools.', outcomes: ['Match redundancy to resilience needs', 'Use SAS without overexposing access', 'Protect data with versions, soft delete, and lifecycle rules'] },
  { name: 'Compute', weight: '20–25%', accent: 'amber', focus: 'Bicep/ARM, VMs, disks, availability, scale sets, containers, App Service.', outcomes: ['Pick the right compute platform', 'Read a Bicep deployment before changing it', 'Design availability and scale deliberately'] },
  { name: 'Networking', weight: '15–20%', accent: 'green', focus: 'VNets, peering, NSGs, UDRs, private endpoints, DNS, load balancing, troubleshooting.', outcomes: ['Trace a packet through NSG and routing decisions', 'Distinguish service endpoints from private endpoints', 'Use Network Watcher evidence before changing a rule'] },
  { name: 'Monitor & maintain', weight: '10–15%', accent: 'rose', focus: 'Metrics, logs, alerts, Insights, Backup, Site Recovery, recovery testing.', outcomes: ['Choose metrics versus logs', 'Build alerts with an actionable response', 'Prove a restore plan rather than assuming one works'] },
];

const labs = [
  { title: 'Govern a small platform', time: '50 min', area: 'Identity & governance', goal: 'Build a sensible hierarchy for a fictional company and keep production from being accidentally changed.', tasks: ['Create rg-az104-lab and apply CostCenter + Environment tags', 'Assign Reader at the resource-group scope to a test user or group', 'Add a CanNotDelete lock, then observe the blocked delete attempt', 'Create a budget alert; remove every lab resource afterward'], debrief: 'RBAC controls who may act. Policy evaluates or enforces standards. A lock protects against accidental management-plane changes.' },
  { title: 'Storage with a recovery story', time: '55 min', area: 'Storage', goal: 'Create a storage account that supports limited access and recoverable blobs without leaving costs behind.', tasks: ['Create a standard storage account and compare LRS / ZRS / GRS in the portal', 'Create a private blob container, upload a sample file, then issue a time-limited SAS', 'Enable blob versioning and soft delete; overwrite and restore the sample', 'Add a lifecycle rule with a testable prefix, then delete the account'], debrief: 'Data-plane access and management-plane access are different. A SAS is delegated, bounded access—not a replacement for least-privilege design.' },
  { title: 'Private application network', time: '70 min', area: 'Networking', goal: 'Connect an app subnet to a private service while documenting every hop a packet takes.', tasks: ['Create a VNet with app and data subnets; reserve address space intentionally', 'Create an NSG with a narrowly scoped allow rule and inspect effective rules', 'Create a private endpoint for a supported PaaS service and validate private DNS linkage', 'Use Network Watcher tools to diagnose a deliberately blocked connection'], debrief: 'Private endpoints give a private IP in your VNet. NSG evaluation and routes are separate questions; troubleshoot with evidence.' },
  { title: 'Recoverable workload', time: '60 min', area: 'Monitor & maintain', goal: 'Make a small VM workload observable and prove that a recovery path exists.', tasks: ['Create a low-cost lab VM only if quota and billing allow; otherwise use a guided portal review', 'Create a Log Analytics workspace and inspect VM insights prerequisites', 'Create a metric alert with an action group, then review the alert processing flow', 'Create a vault and walk through a backup policy and restore-point selection; delete resources'], debrief: 'Monitoring tells you what happened; backup and recovery tell you what you can restore. Treat a restore test as the acceptance criterion.' },
];

const flashcards = [
  ['RBAC vs Azure Policy', 'RBAC decides who can perform an action. Policy evaluates or enforces what resources/configurations are allowed.'],
  ['Resource lock', 'A management-plane safeguard: CanNotDelete blocks deletes; ReadOnly also blocks changes. It does not block data-plane operations.'],
  ['Service endpoint vs private endpoint', 'A service endpoint keeps the service public but extends VNet identity; a private endpoint maps the service to a private IP in your VNet.'],
  ['Metric vs log', 'Metrics are lightweight numeric time series, ideal for near-real-time alerting. Logs are richer records queried with KQL.'],
  ['LRS / ZRS / GRS', 'LRS replicates within one datacenter; ZRS across availability zones in a region; GRS also replicates to a paired secondary region.'],
  ['Availability set vs zone', 'A set spreads VMs across fault/update domains within a datacenter; zones place resources in physically separate datacenters in a region.'],
  ['NSG rule processing', 'Rules are evaluated by priority (lowest number first); an explicit allow can match before the default deny. Inbound and outbound are separate.'],
  ['Bicep', 'A declarative language that compiles to ARM JSON. Think desired state, parameters, resources, dependencies, and outputs.'],
  ['SAS', 'A signed, limited delegation for Storage access. Scope permissions, resource, protocol, and expiration as tightly as possible.'],
  ['Azure Backup vs Site Recovery', 'Backup restores data/workloads from recovery points. Site Recovery replicates workloads for failover and disaster recovery.'],
];

const questions = [
  { q: 'A finance team needs to view every resource in one production resource group but must not change anything. What is the least-privileged choice?', options: ['Owner at subscription', 'Reader at the resource group', 'Contributor at the resource group', 'Reader at management group'], answer: 1, why: 'Reader at the required resource-group scope gives visibility without write permission or unnecessary wider access.' },
  { q: 'A storage account must survive a zonal failure inside its primary region. Which redundancy option best directly meets that requirement?', options: ['LRS', 'ZRS', 'GRS', 'RA-GRS'], answer: 1, why: 'ZRS synchronously replicates across availability zones in one region. GRS adds regional replication but is not the direct answer for the stated zonal requirement.' },
  { q: 'A PaaS service must be reachable through a private IP from a VNet. Which feature is the fit?', options: ['Service endpoint', 'Private endpoint', 'Public IP', 'NSG service tag'], answer: 1, why: 'A private endpoint creates a network interface with a private IP in the VNet for the supported PaaS resource.' },
  { q: 'You need to retain blobs for 30 days after accidental deletion and recover an earlier overwritten version. Which pair matters most?', options: ['Lifecycle rule and immutable storage', 'Soft delete and blob versioning', 'SAS and access keys', 'Snapshots and a public container'], answer: 1, why: 'Soft delete protects deleted data during retention; versioning preserves prior blob versions after overwrites.' },
  { q: 'An alert needs to trigger when CPU stays high for five minutes. What data type should you start with?', options: ['Activity log', 'Metric', 'Resource lock', 'Azure Policy compliance state'], answer: 1, why: 'CPU utilization is a time-series metric; metrics are the direct foundation for this near-real-time threshold alert.' },
  { q: 'An app must scale identical stateless VM instances based on demand. What is the natural Azure compute choice?', options: ['Availability set', 'Virtual Machine Scale Set', 'Recovery Services vault', 'Azure Bastion'], answer: 1, why: 'VM Scale Sets manage a group of load-balanced VMs and support scaling patterns for homogeneous workloads.' },
  { q: 'A policy assignment at subscription scope denies public IP resources. Where does the assignment apply by inheritance?', options: ['Only directly created subscriptions', 'All resource groups and resources in that subscription', 'Only resources tagged Production', 'Only a selected VNet'], answer: 1, why: 'Management settings at subscription scope flow to child resource groups and resources unless an applicable exemption is configured.' },
  { q: 'A workload needs a named repeatable deployment definition instead of hand-created portal resources. What is the best first tool?', options: ['Bicep', 'Azure Advisor', 'Network Watcher', 'Storage Explorer'], answer: 0, why: 'Bicep expresses Azure infrastructure declaratively and compiles to ARM templates for repeatable deployments.' },
];

const scenarios = [
  { title: 'Contoso’s risky deployment', brief: 'A developer needs to deploy a web app and storage account into production. The security team requires no public data access and wants an audit trail. The finance team wants costs attributed to the project.', prompts: ['Which scope gets the developer role, and which role?', 'What controls enforce no public access versus prevent accidental deletion?', 'Which two tags improve cost ownership?', 'What evidence would you collect after deployment?'] },
  { title: 'The “website is down” call', brief: 'An internal web app on two VMs is unreachable from one office. The VMs appear healthy. A network change was made yesterday.', prompts: ['State your troubleshooting order before editing any NSG.', 'Which Network Watcher capability or evidence helps at each step?', 'How do effective rules and user-defined routes change the investigation?', 'What is your rollback and validation plan?'] },
  { title: 'Quarter-end restore request', brief: 'A user deleted a blob yesterday, and a finance analyst needs the version from last week. The storage account has versioning and soft delete enabled.', prompts: ['Which protection feature addresses each part of the request?', 'How would you restore with the least disruption?', 'What access would the analyst need versus the storage administrator?', 'What will you document for the post-incident review?'] },
];

function SectionTitle({ eyebrow, title, body }: { eyebrow: string; title: string; body: string }) { return <div className="section-title"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p className="lede">{body}</p></div>; }

export default function Home() {
  const [active, setActive] = useState('plan'); const [card, setCard] = useState(0); const [flipped, setFlipped] = useState(false); const [answers, setAnswers] = useState<Record<number, number>>({}); const [submitted, setSubmitted] = useState(false); const [doneLabs, setDoneLabs] = useState<number[]>([]);
  const score = useMemo(() => Object.entries(answers).filter(([i, a]) => questions[Number(i)].answer === a).length, [answers]);
  const days = Math.max(0, Math.ceil((new Date('2026-09-17T09:00:00').getTime() - Date.now()) / 86400000));
  const nav = [{ id: 'plan', label: 'Study sprint' }, { id: 'guide', label: 'Concept guide' }, { id: 'labs', label: 'Tenant labs' }, { id: 'practice', label: 'Practice exam' }, { id: 'cards', label: 'Flashcards' }, { id: 'scenarios', label: 'Scenarios' }];
  const go = (id: string) => { setActive(id); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); };
  useEffect(() => {
    const context = (document as Document & { modelContext?: { registerTool: (tool: Record<string, unknown>, options: { signal: AbortSignal }) => void | Promise<void> } }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    const register = (tool: Record<string, unknown>) => Promise.resolve(context.registerTool(tool, { signal: lifecycle.signal })).catch(() => undefined);
    void register({ name: 'read_az104_progress', title: 'Read AZ-104 progress', description: 'Read the current study-site progress, including reviewed labs and answered original practice questions.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: false }, execute: () => ({ reviewedLabs: doneLabs.length, totalLabs: labs.length, answeredQuestions: Object.keys(answers).length, totalQuestions: questions.length, checkedScore: submitted ? score : null }) });
    void register({ name: 'set_az104_lab_reviewed', title: 'Set lab review status', description: 'Mark one visible tenant lab as reviewed or not reviewed. Use after completing or reviewing that lab.', inputSchema: { type: 'object', properties: { labNumber: { type: 'integer', minimum: 1, maximum: labs.length }, reviewed: { type: 'boolean' } }, required: ['labNumber', 'reviewed'], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: (input) => { if (!input || typeof input !== 'object' || !('labNumber' in input) || !('reviewed' in input) || typeof input.labNumber !== 'number' || !Number.isInteger(input.labNumber) || input.labNumber < 1 || input.labNumber > labs.length || typeof input.reviewed !== 'boolean') throw new Error('labNumber must be an integer from 1 to 4 and reviewed must be a boolean.'); const index = input.labNumber - 1; setDoneLabs(current => input.reviewed ? (current.includes(index) ? current : [...current, index]) : current.filter(value => value !== index)); return { labNumber: input.labNumber, reviewed: input.reviewed }; } });
    return () => lifecycle.abort();
  }, [answers, doneLabs, score, submitted]);
  return <main>
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">A</span><span>AZ-104 <b>Field Guide</b></span></a><nav aria-label="Primary navigation">{nav.map(item => <button key={item.id} className={active === item.id ? 'nav-active' : ''} onClick={() => go(item.id)}>{item.label}</button>)}</nav></header>
    <section id="top" className="hero"><div className="hero-copy"><p className="eyebrow hero-eyebrow"><Target size={14} /> Administrator Associate prep</p><h1>Learn Azure by <em>running</em> it.</h1><p className="hero-text">A focused field guide for your September 17 AZ-104 exam: weighted objectives, original practice, tenant-ready labs, and operational scenarios.</p><div className="hero-actions"><button className="primary" onClick={() => go('plan')}>Start the sprint <ArrowRight size={17} /></button><a className="text-link" href="https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-104" target="_blank" rel="noreferrer">Official skills outline <ExternalLink size={14} /></a></div></div><aside className="exam-card"><div className="exam-top"><span>EXAM TARGET</span><Clock3 size={18} /></div><strong>September 17</strong><p>{days > 0 ? `${days} days to convert recognition into judgment.` : 'Exam day: focus on calm, evidence-based choices.'}</p><div className="exam-rule"><span>Pass score</span><b>700+</b></div><div className="exam-rule"><span>Core domains</span><b>5</b></div></aside></section>
    <section id="plan" className="section surface plan" onMouseEnter={() => setActive('plan')}><SectionTitle eyebrow="Your runway" title="A 9-session sprint that matches the blueprint" body="Spend the most time where the exam spends the most time: governance and compute. Each session ends with a decision, a lab action, and a short recall loop." /><div className="sprint-grid">{[['1','Baseline & tools','Run the official practice assessment; set up Cloud Shell; identify your weakest domain.'],['2','Identity & governance','RBAC scope, Policy versus locks, tags, management groups, budgets.'],['3','Storage','Redundancy, access, SAS, Azure Files, Blob protection and lifecycle.'],['4','Compute','Bicep, VMs, disks, availability, scale sets, containers, App Service.'],['5','Networking','Addressing, peering, NSGs, UDRs, private access, DNS, load balancing.'],['6','Monitor & recovery','Metrics/logs, alerts, Insights, Backup and Site Recovery.'],['7','Integrated tenant day','Complete two labs from start to cleanup. Narrate every design decision.'],['8','Timed practice + repair','Take a timed original/official assessment. Rebuild the two weakest concepts.'],['9','Light recall','Flashcards, diagrams, service-selection comparisons, sleep. No new broad topics.']].map(([n,title,text]) => <article className="sprint" key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><div className="tip"><CircleAlert size={18} /><span><b>Study rule:</b> when you miss a question, write why each wrong answer is wrong. That turns memorized names into operational judgment.</span></div></section>
    <section id="guide" className="section" onMouseEnter={() => setActive('guide')}><SectionTitle eyebrow="The blueprint" title="Five domains; one connected operating model" body="These weights reflect Microsoft’s current skills-measured guide. Use them to decide where your next study hour goes—not as a substitute for the official outline." /><div className="topic-grid">{topics.map(topic => <article className="topic" key={topic.name}><div className={`topic-bar ${topic.accent}`} /><div className="topic-head"><h3>{topic.name}</h3><b>{topic.weight}</b></div><p>{topic.focus}</p><ul>{topic.outcomes.map(x => <li key={x}><Check size={15} />{x}</li>)}</ul></article>)}</div><div className="decision-map"><div><p className="eyebrow hero-eyebrow">Decision lens</p><h3>Ask these four questions on every scenario</h3></div><ol><li><b>Scope:</b> tenant, management group, subscription, resource group, or resource?</li><li><b>Plane:</b> management action, data access, or network traffic?</li><li><b>Control:</b> access, governance, resiliency, performance, or cost?</li><li><b>Evidence:</b> metric, log, effective rule, activity log, or restore test?</li></ol></div></section>
    <section id="labs" className="section surface" onMouseEnter={() => setActive('labs')}><SectionTitle eyebrow="Use your tenant" title="Labs that build administrator instinct" body="These exercises deliberately use small, reversible resources. Check your subscription’s prices, quotas, and regional availability before creating anything; delete the resource group at the end." /><div className="lab-grid">{labs.map((lab, index) => <article className="lab" key={lab.title}><div className="lab-meta"><span>{lab.area}</span><span><Clock3 size={14} /> {lab.time}</span></div><h3>{lab.title}</h3><p>{lab.goal}</p><ol>{lab.tasks.map(task => <li key={task}>{task}</li>)}</ol><div className="debrief"><FlaskConical size={17} /><span>{lab.debrief}</span></div><button className={doneLabs.includes(index) ? 'complete' : 'outline'} onClick={() => setDoneLabs(current => current.includes(index) ? current.filter(x => x !== index) : [...current, index])}>{doneLabs.includes(index) ? <><Check size={16} /> Lab reviewed</> : 'Mark lab reviewed'}</button></article>)}</div></section>
    <section id="practice" className="section" onMouseEnter={() => setActive('practice')}><SectionTitle eyebrow="Original question set" title="Practice choosing the best answer, not just a true answer" body="Eight original, scenario-style questions. Do this closed-book first, then use each explanation to repair the underlying concept. This is preparation material—not an exam brain dump." /><div className="quiz-shell">{questions.map((item, index) => <article className="question" key={item.q}><p className="question-num">Question {index + 1}</p><h3>{item.q}</h3><div className="answers">{item.options.map((option, optionIndex) => { const selected = answers[index] === optionIndex; const correct = item.answer === optionIndex; return <button key={option} onClick={() => !submitted && setAnswers({ ...answers, [index]: optionIndex })} className={`answer ${selected ? 'chosen' : ''} ${submitted && correct ? 'correct' : ''} ${submitted && selected && !correct ? 'incorrect' : ''}`}><span>{String.fromCharCode(65 + optionIndex)}</span>{option}</button>; })}</div>{submitted && <p className="explanation"><b>Why:</b> {item.why}</p>}</article>)}<div className="quiz-footer"><div><span className="eyebrow">Result</span><h3>{submitted ? `${score} / ${questions.length} correct` : `${Object.keys(answers).length} answered`}</h3></div><button className="primary" onClick={() => submitted ? (setAnswers({}), setSubmitted(false)) : setSubmitted(true)}>{submitted ? 'Try again' : 'Check answers'} <ArrowRight size={17} /></button></div></div></section>
    <section id="cards" className="section surface cards-section" onMouseEnter={() => setActive('cards')}><SectionTitle eyebrow="Active recall" title="Flashcards for the distinctions exam questions exploit" body="Say the answer before revealing it. If you hesitate, open the linked Microsoft Learn material and make the comparison in your own words." /><div className="flashcard-wrap"><button className="card-arrow" aria-label="Previous flashcard" onClick={() => { setCard((card + flashcards.length - 1) % flashcards.length); setFlipped(false); }}><ChevronLeft /></button><button className={`flashcard ${flipped ? 'flipped' : ''}`} onClick={() => setFlipped(!flipped)} aria-label="Reveal flashcard answer"><div className="flash-front"><span>CONCEPT {card + 1} / {flashcards.length}</span><h3>{flashcards[card][0]}</h3><p>Click to reveal</p></div><div className="flash-back"><span>ANSWER</span><p>{flashcards[card][1]}</p></div></button><button className="card-arrow" aria-label="Next flashcard" onClick={() => { setCard((card + 1) % flashcards.length); setFlipped(false); }}><ChevronRight /></button></div></section>
    <section id="scenarios" className="section" onMouseEnter={() => setActive('scenarios')}><SectionTitle eyebrow="Think like an administrator" title="Talk through the trade-offs out loud" body="Use these prompts with a timer. Explain your design before touching the portal; then test the minimum viable version in your tenant." /><div className="scenario-grid">{scenarios.map((scenario, i) => <article className="scenario" key={scenario.title}><div className="scenario-icon">{i === 1 ? <Network /> : i === 2 ? <Layers3 /> : <ShieldCheck />}</div><h3>{scenario.title}</h3><p>{scenario.brief}</p><ol>{scenario.prompts.map(prompt => <li key={prompt}>{prompt}</li>)}</ol></article>)}</div></section>
    <section className="section sources"><SectionTitle eyebrow="Sources & next actions" title="Use Microsoft’s living materials as the final authority" body="Microsoft updates certification objectives periodically. Before your final practice session, verify the skills outline and take the official assessment through your Microsoft Learn profile." /><div className="source-list"><a href="https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-104" target="_blank" rel="noreferrer"><BookOpen size={18} /><span><b>Study guide for Exam AZ-104</b><small>Skills measured as of April 17, 2026; domain weights, objectives, practice assessment and exam sandbox links.</small></span><ExternalLink size={16} /></a><a href="https://learn.microsoft.com/en-us/training/courses/az-104t00" target="_blank" rel="noreferrer"><BookOpen size={18} /><span><b>Microsoft Azure Administrator course (AZ-104T00-A)</b><small>Four-day course scope across subscriptions, identity, infrastructure, networking, storage, compute, backup, and monitoring.</small></span><ExternalLink size={16} /></a><a href="https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/overview" target="_blank" rel="noreferrer"><BookOpen size={18} /><span><b>Azure Resource Manager overview</b><small>Management scopes, deployment model, RBAC integration, tags, and resource-group behavior.</small></span><ExternalLink size={16} /></a></div></section>
    <footer><span>AZ-104 Field Guide</span><span>Built for hands-on learning · September 2026</span></footer>
  </main>;
}
